---
driver:
  name: docker
  use_sudo: false
  ssh:
    pty: true

provisioner:
  name: ansible_playbook
  roles_path: roles
  hosts: localhost
  ansible_version: latest
  ansible_verbose: true
  ansible_verbosity: 4
  require_ansible_repo: true
  require_chef_for_busser: false
  require_ruby_for_busser: true
  private_key: spec/insecure_key/insecure_key
  ansible_host_key_checking: false
  ansible_connection: ssh

platforms:
  - name: ubuntu-14.04
    driver:
      image: ubuntu:14.04
      platform: ubuntu
      instance_name: ansible
      publish_all: true
  # - name: ansible
  #   driver_plugin: docker
  #   driver:
  #     image: ubuntu:14.04
  #     platform: ubuntu
  #     instance_name: ansible.openresty.dev
  #     publish_all: true
  #     # links: "opsboy.openresty.dev:opsboy.openresty.dev"

verifier:
  name: busser
  plugin:
  - Ansiblespec
  ruby_bindir: '/usr/bin'

suites:
  - name: ansible
    driver_config:
      hostname: ansible.openresty.dev

  # - name: opsboy
  #   excludes:
  #     - ansible
  #   driver_config:
  #     hostname: opsboy.openresty.dev
